version: "2"
linters:
  disable:
    - staticcheck
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/tencentcloud/tencentcloud-cls-sdk-go.AsyncProducerClient).Close
        - (io.ReadCloser).Close
        - (io.Closer).Close
        - (*os.File).Close
        - (*net.Conn).Close
